config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get "home/index"
  get "home/about"
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: %i[ index show ]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twitter, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %>
      prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div class="mb-3">

  <div class="mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone n°..." %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"@Twitter..." %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id , class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="mb-3">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id(friend) %>">
  <td><%= friend.first_name %></td>
  <td><%= friend.last_name %></td>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.twitter %></td>
  <td><%= friend.user_id %></td>
  <td>
    <%= link_to "Show", friend_path(friend), class: "btn btn-sm btn-dark" %>
    <%= link_to "Edit", edit_friend_path(friend), class: "btn btn-sm btn-dark" %>
    <%= button_to "Delete", friend_path(friend), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-secondary" %>
  </td>
</tr>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1>Editing friend</h1>
</br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-light" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-light" %>
</div>

app/views/friends/index.html.erb
<% content_for :title, "Friends" %>

<h1>All friends</h1>

<table class="table table-dark table-hover table-striped-columns table-bordered border-secondary">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>user_id</th>
      <th>Actions</th>

    </tr>
  </thead>

  <tbody id="friends">
      <%= render @friends %>
  </tbody>
</table>

<%= link_to "Add new friend", new_friend_path, class:"btn btn-dark" %>

app/views/friends/new.html.erb
<% content_for :title, "Add new friend" %>

<h1>Add new friend</h1>
</br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-light" %>
</div>

app/views/friends/show.html.erb
<div class="card" style="width: 50rem">
  <img src="https://live.staticflickr.com/7610/17236741316_f9554bbb48_b.jpg" class="card-img-top" alt="two dudes old friends">
  <div class="card-body">
    <h5 class="card-title">
      <strong>First name:</strong>
      <%= @friend.first_name %>
    </h5>
    <h5>
      <strong>Last name:</strong>
      <%= @friend.last_name %>
    </h5>
    <div class="card-body">
      <p>
        <strong>Email:</strong>
        <%= @friend.email %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= @friend.phone %>
      </p>
      <p>
        <strong>Twitter:</strong>
        <%= @friend.twitter %>
      </p>

    </div>
    <div>
        <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-sm btn-dark" %> |
        <%= link_to "Back to friends", friends_path, class:"btn btn-sm btn-dark" %>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark ">

  <div class="container-fluid">
    <%= link_to 'RailsFriends', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All friends", friends_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add new friend", new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out...", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In!", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up!", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>

      </ul>

      <form class="d-flex" role="search">

        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-light" type="submit">Search</button>

      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us ...</h1>

app/views/home/index.html.erb
<h1>HEY !</h1>
<p>This is  my first ROR site!</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-light alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rails Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>